#!/bin/sh
# ~/.xprofile -- Intended to be sourced a single time when the computer starts

# PATH-related variables
[ -d "$HOME/bin" ] && export PATH="$PATH:$HOME/bin"
[ -d "$HOME/bin/scripts" ] && export PATH="$PATH:$HOME/bin/scripts"
[ -d "$HOME/.cargo/bin" ] && export PATH="$PATH:$HOME/.cargo/bin"
[ -d "$HOME/.cabal/bin" ] && export PATH="$PATH:$HOME/.cabal/bin"

# For Ruby stuff:
if command -v ruby >/dev/null 2>&1; then
    export GEM_HOME=$(ls | ruby -e 'puts Gem.user_dir')
    export GEM_PATH=$GEM_HOME
    [ -d "$GEM_PATH" ] && export PATH="$PATH:$GEM_HOME/bin"
fi

if command -v java >/dev/null 2>&1; then
    # Fix font rendering in Java applications, but make it so that
    # "Picked up _JAVA_OPTIONS" isn't shown
    _SILENT_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true'
    unset _JAVA_OPTIONS
    alias java='java "$_SILENT_JAVA_OPTIONS"'

    # For ENSIME, tool for helping with JVM languages
    [ -f "/usr/lib/jvm/java-7-openjdk/lib/tools.jar" ] && export JDK_HOME="/usr/lib/jvm/java-7-openjdk"
    [ -f "/usr/lib/jvm/java-8-openjdk/lib/tools.jar" ] && export JDK_HOME="/usr/lib/jvm/java-8-openjdk"
    [ -d "/usr/lib/jvm/default" ] && export JAVA_HOME="/usr/lib/jvm/default"
fi

# For Racer-Rust, the location of the Rust source code
if command -v cargo >/dev/null 2>&1; then
    if [ -d "$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src" ]; then
        export RUST_SRC_PATH="$HOME/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"
    elif [ -d "$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src" ]; then
        export RUST_SRC_PATH="$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src"
    fi

    # Enable incremental compilation, for faster compile times
    export CARGO_INCREMENTAL="1"
fi

# Prevent issues when using the Android Studio Android Emulator
if command -v android-studio >/dev/null 2>&1; then
    export ANDROID_HOME=/opt/android-sdk
    export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
fi

# Start the gnome-keyring-daemon, if installed
if command -v gnome-keyring-daemon >/dev/null 2>&1; then
    eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
    export SSH_AUTH_SOCK
fi

# Start MPD if not already running
[ ! -s "$HOME/.config/mpd/pid" ] && mpd

# Set the keyboard layout
setxkbmap dvorak
