#!/bin/bash
## Author: ben01189998819991197253
# Script to replace all instances of a string in a file with another string.
##

set -o errexit          # Exit on most errors (see the manual)
set -o errtrace         # Make sure any error trap is inherited
set -o nounset          # Disallow expansion of unset variables
set -o pipefail         # Use last non-zero exit code in a pipeline
#set -o xtrace          # Trace the execution of the script (debug)

usage() {
    echo -e "Usage: replaceall [-ih] \"old_string\" \"new_string\" file"
}

while getopts ih flag; do
    case "$flag" in
	i)
	    case_insensitive=1;;
	h)
	    usage
	    exit 0;;
	*)
	    usage
	    exit 1;;
    esac
done

shift $((OPTIND - 1))

GREEN="\033[0;32m"
RED="\033[0;31m"
NC="\033[0m" # No color

if [[ $# -ne 3 ]]; then
    echo -e "${RED}Incorrect number of parameters passed.${NC}" >&2
    usage
    exit 1
fi

if [[ ! -f $3 ]]; then
    echo -e "${RED}File passed as parameter does not exist!${NC}" >&2
    usage
    exit 1
fi

if [[ $case_insensitive -eq 1 ]]; then
    num_instances=$(grep -ioc "$1" "$3")
else
    num_instances=$(grep -oc "$1" "$3")
fi

echo -ne "Found ${GREEN}$num_instances${NC} instance(s) of \"$1\""
if [[ $case_insensitive -eq 1 ]]; then
    echo " (case insensitive), replacing..."
    ex -sc ':set ignorecase
	%s/'"$1"'/'"$2"'/g|x' "$3"
else
    echo ", replacing..."
    ex -sc '%s/'"$1"'/'"$2"'/g|x' "$3"
fi
