#!/bin/sh
## Author: ben01189998819991197253
# Script to automatically generate HTML whenever a Markdown
# file or a directory with Markdown files is modified.
# Only generates HTML for files ending in .md or .markdown.
# POSIX sh-compatible.
# Dependencies: inotify-tools, markdown
##

set -o errexit          # Exit on most errors (see the manual)
set -o errtrace         # Make sure any error trap is inherited
set -o nounset          # Disallow expansion of unset variables
set -o pipefail         # Use last non-zero exit code in a pipeline
#set -o xtrace          # Trace the execution of the script (debug)

trap 'exit 0' INT

if [ ! -e "$1" ]; then
	echo "File or directory passed as argument doesn't exist." >&2
	exit 1
fi

markdown_file() {
	if [ -f "$1" ]; then
		echo "$1" | grep -qi -E '\.md$|\.markdown$|\.mdown$|\.mkdn$|\.mkd$'
		if [ $? -eq 0 ]; then
			file_path="$(realpath -- "$1")"
			html_file="${file_path%.*}.html"
			markdown "$1" > "$html_file"
		fi
	fi
}

markdown_directory() {
	for file in "$1/"*; do
		# File existence-checking is done in markdown_file()
		markdown_file "$file"
	done
}

if [ -d "$1" ]; then
	markdown_directory "$1"
else
	markdown_file "$1"
fi

echo "Watching $1 for changes."

while inotifywait -qq -e modify,attrib -- "$1"; do
	if [ -d "$1" ]; then
		echo " >>> The contents of $1 have changed."
		markdown_directory "$1"
	else
		echo " >>> File $1 has changed."
		markdown_file "$1"
	fi
done
