#!/bin/bash
## Author: ben01189998819991197253
# Script to fetch and display your internal and external IP addresses.
# Only works with IPv4.
##

set -o errexit          # Exit on most errors (see the manual)
set -o errtrace         # Make sure any error trap is inherited
set -o nounset          # Disallow expansion of unset variables
set -o pipefail         # Use last non-zero exit code in a pipeline
#set -o xtrace          # Trace the execution of the script (debug)

RED="\033[0;31m"
NC="\033[0m" # No color

ping -q -w 1 -c 1 192.168.0.1 &> /dev/null

if [[ ! $? -eq 0 ]]; then
	echo -e "${RED}You're not connected to a network.${NC}" >&2
	exit 1
fi

external=$(curl -s http://ipecho.net/plain)
internal=$(ip addr | grep 'state UP' -A2 | tail -n1 | \
		   awk '{print $2}' | cut -f1 -d'/')

echo -e "EXTERNAL        \t INTERNAL       "
echo -e "=============== \t ==============="
echo -e "$external       \t $internal      "
